spring:
  application.name: recordMCI

logging.level:
  org.hibernate:
    SQL: debug
    orm.jdbc.bind: trace

--- #prod
spring:
  config.activate.on-profile: prod

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:recordmci.db?busy_timeout=30000&journal_mode=WAL&synchronous=NORMAL&cache_size=10000&temp_store=MEMORY
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 300
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: true
        highlight_sql: true

  sql.init.mode: always  # schema.sql 실행

--- #local
spring:
  config.activate.on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/recordmci
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  h2:
    console:
      enabled: true
      path: /console
